plugins {
    id 'com.android.application'
}

android {
    namespace 'com.capfroggy.simpleautoclicker'
    compileSdk 35

    defaultConfig {
        applicationId 'com.capfroggy.simpleautoclicker'
        minSdk 24
        targetSdk 35
        versionCode 5
        versionName '1.2.1'
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
}
